---
# Source: guestbook-stack/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gbapp-backend
  labels:
    app: gb
    env: dev
    stack: guestbook
spec:
  selector:
    matchLabels:
      app: gb
      env: dev
      stack: guestbook
  replicas: 3
  template:
    metadata:
      labels:
        app: gb
        env: dev
        stack: guestbook
    spec:
      containers:
      - name: gbapp-backend
        image: krutipatel15/guestbook-helm-backend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
