---
# Source: guestbook-stack/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gbapp-backend
  labels:
    app: gb
    env: dev
    stack: guestbook
spec:
  selector:
    matchLabels:
      app: gb
      env: dev
      stack: guestbook
  replicas: 3
  template:
    metadata:
      labels:
        app: gb
        env: dev
        stack: guestbook
    spec:
      containers:
      - name: gbapp-backend
        image: wordpress:latest
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: gbapp-backend-configmap
              optional: false
          - secretRef:
              name: gbapp-backend-secret
              optional: false
        ports:
        - containerPort: 5001
