---
# Source: guestbook-stack/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gbapp-backend-service
  labels:
    app: gb
    env: dev
    stack: guestbook
spec:
  ports:
  - port: 80            # the port on which the service is listening
    protocol: TCP
    targetPort: 5001      # the port exposed by Pod (we defined in the deployment as part of `containerPort)
  type: ClusterIP
  selector:
    app: gb
    env: dev
    stack: guestbook       # Pod label that service is using to select Pods
