---
# Source: guestbook-stack/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-app-deployment
  labels:
    app: guestbook
    env: dev
    stack: guestbook
spec:
  selector:
    matchLabels:
      app: guestbook
      env: dev
      stack: guestbook
  replicas: 3
  template:
    metadata:
      labels:
        app: guestbook
        env: dev
        stack: guestbook
    spec:
      containers:
      - name: guestbook-app
        image: wordpress:latest
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: guestbook-app-configmap
              optional: false
          - secretRef:
              name: guestbook-app-secret
              optional: false
        ports:
        - containerPort: 5000
