version: "3.8"

services:

  frontend:
    build:
      context: ./frontend
    image: krutipatel15/guestbookapp-frontend:v1
    ports:
      - "5000:5000"
    depends_on:
      - backend
    deploy:
      replicas: 1
    networks:
      - guestbook-network


  backend:
    build:
      context: ./backend
    image: krutipatel15/guestbookapp-backend:v1
    deploy:
      replicas: 1
    networks:
      - guestbook-network
    ports:
      - "5001:5001"


networks:
  guestbook-network:
    driver: overlay
