version: "3.8"

services:
  frontend:
    image: krutipatel15/guestbook-helm-frontend:v1
    ports:
      - "5000:5000"
    depends_on:
      - backend
    deploy:
      replicas: 1
    networks:
      - guestbook-net

  backend:
    image: krutipatel15/guestbook-helm-backend:v1
    deploy:
      replicas: 1
    networks:
      - guestbook-net
    ports:
      - "5001:5001"

networks:
  guestbook-net:
    driver: overlay  # Ensure overlay driver is specified
    #external: false   # Do not use an external network; create a swarm-specific network
