apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.gb.name }}-configmap
  labels:
{{- toYaml .Values.gb.labels | nindent 4 }}
data:
{{- range $k, $v := .Values.gb.configmap }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
