apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.gb.name }}-deployment
  labels:
{{- toYaml .Values.gb.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
{{- toYaml .Values.gb.labels | nindent 6 }}
  replicas: 3
  template:
    metadata:
      labels:
{{- toYaml .Values.gb.labels | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.gb.name }}
        image: {{ .Values.gb.image.repository }}:{{ .Values.gb.image.tag }}
        imagePullPolicy: {{ .Values.gb.image.pullPolicy }}
        envFrom:
          - configMapRef:
              name: {{ .Values.gb.name }}-configmap
              key: BACKEND_URL
        ports:
          - containerPort: {{ .Values.gb.containerPorts.http }}
