gb:
  name: guestbook-app
  labels:
    app: guestbook-app
    env: dev
    stack: guestbook
  image:
    repository: wordpress
    tag: latest
    pullPolicy: Always
  replicas: 2
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
  resources:
    requests:
      cpu: "150m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"
  configmap:
    ## KEY: "value"
    BACKEND_URL: "wp-database.wpdb.svc.cluster.local:3306"
    APP_ENV: dev
  containerPorts:
      http: 5000
